-
  name: Install Java and Docker
  hosts: server
  become: yes 
  tasks:
    - name: Install Java
      apt: name=openjdk-11-jdk update-cache=yes state=latest
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true
  
